# Generated by Django 6.0.7 on 2026-09-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
