# Generated by Django 6.0.7 on 2026-07-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
