# Generated by Django 6.0.7 on 2026-07-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_person_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
