# Generated by Django 6.0.7 on 2026-07-28 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_cart3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart3',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart3',
            name='user',
        ),
        migrations.CreateModel(
            name='PanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10)),
                ('full_name', models.TextField()),
                ('image', models.ImageField(upload_to='pancard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.person')),
            ],
        ),
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='Main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart2',
        ),
        migrations.DeleteModel(
            name='Cart3',
        ),
    ]
